# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: samajdarsoumyajeet0@gmail.com
author_name: soumyo-jeet
contract_name: lottery_contract
deployment_language: python
preset_name: production
project_name: lottery-smart-contract

